### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by florisre** [MichaelSebero/PrivateGPT4Linux#2]
If I am not mistaken, this also needs `gcc` and `g++` installed, which not necessarily are installed already. Also, does the user need to change the `settings.yaml` to include a huggingface access token?

**Comment by Michael-Sebero** [comment]
I'm not sure if you need those installed but I could be wrong. Recently I used my installer on a fresh install of Artix and it installed correctly. You don't need a huggingface access token to use this script either.

**Comment by florisre** [comment]
Well, the script did not work without `g++` and did work with it on Fedora.
