### ISSUE TITLE
break-system-packages not working?

### ISSUE THREAD

**Issue by stevencheist** [MichaelSebero/PrivateGPT4Linux#4]
I'm getting an error that says there's no option for --break-system-packages... could be the arm compatible ubuntu version I'm using on vmware fusion on my m1 mac I suppose, wondering if you're hearing this from anyone else.

steven@gpt:~/privateGPT$ hostnamectl
 Static hostname: gpt
       Icon name: computer-vm
         Chassis: vm
      
  Virtualization: vmware
Operating System: Ubuntu 22.04.2 LTS              
          Kernel: Linux 5.15.0-78-generic
    Architecture: arm64
 Hardware Vendor: VMware, Inc.
  Hardware Model: VMware20,1
 python3 --version
Python 3.10.12

thanks for putting this together!  hoping this is helpful. 

if I edit your installer script to take away that option it further installs but the requirements.txt file from the other repo you're cloning looks for a version of gpt4all that isn't available on the update server configured (only has highest of 0.1.7). - not an issue with your code though.

**Comment by MichaelSebero** [comment]
It's not compatible with Debain Based systems yet, as of right now PrivateGPT4Linux will be for Arch Based systems only.  One day when I learn more about Python Poetry I'll replace Python Pip when it comes to installing requirements. Python Pip released an update this year which made installing requirements more difficult for newer versions so with your older version of Python doesn't need the [ break-system-packages ] option.
